name: "Feature Request"
description: "Suggest an idea for this project"
labels: [enhancement]
title: "[DATE]: [FEATURE NAME]"
assignees:
  - gritcsenko
body:
  - type: textarea
    id: describe-the-feature
    attributes:
      label: "Describe the feature"
      description: "A clear and concise description of what the feature is."
    validations:
      required: true
  - type: textarea
    id: describe-the-solution
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: false
  - type: textarea
    id: describe-alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
