global using System.Collections.Immutable;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using HomeInventory.UI.Models;
global using HomeInventory.UI.Presentation;
global using HomeInventory.UI.DataContracts;
global using HomeInventory.UI.DataContracts.Serialization;
global using HomeInventory.UI.Services.Caching;
global using HomeInventory.UI.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
