global using AutoFixture;
global using AwesomeAssertions;
global using AwesomeAssertions.Execution;
global using HomeInventory.Tests.Framework;
global using HomeInventory.Tests.Framework.Assertions;
global using HomeInventory.Tests.Framework.Attributes;
global using HomeInventory.Tests.Framework.Customizations;
global using Microsoft.Extensions.DependencyInjection;
global using NSubstitute;
