name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CI: true

jobs:
  build:
    name: Build and Test .NET
    runs-on: ubuntu-latest

    steps:
    - name: Checkout files
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: ./src/global.json
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - name: Restore dependencies
      run: dotnet restore --verbosity normal
      working-directory: ./src/HomeInventory
    - name: Build
      run: dotnet build -m:1 --no-incremental --no-restore --configuration Release --self-contained false --verbosity normal
      working-directory: ./src/HomeInventory
    - name: Test All
      run: dotnet test --no-build --no-restore --configuration Release --verbosity normal
      working-directory: ./src/HomeInventory
    - name: Collect Coverage
      run: dotnet test --filter Category=Unit --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory ./coverage
      working-directory: ./src/HomeInventory
    - name: Copy Coverage To Predictable Location
      run: cp coverage/**/coverage.cobertura.xml coverage.cobertura.xml
      working-directory: ./src/HomeInventory
    - name: Code Coverage Summary Report
      id: report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ./src/HomeInventory/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: ${{ github.event_name == 'pull_request' && (success() || steps.report.conclusion == 'failure')}}
      with:
        recreate: true
        path: code-coverage-results.md
    - name: Write coverage to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

